### ISSUE TITLE
Removal of deprecated interfaces for 1.0.9 may break some hub example code

### ISSUE THREAD

**Issue by m-bradshaw** [natmlx/NatML#11]
I've been trying to implement usage of the Hand-Pose model (https://hub.natml.ai/@natsuite/hand-pose), and the code that I downloaded had some errors in HandPosePredictor.cs because it used some interfaces which I saw in the change-log were removed. 

"Removed IMLModel interface as it has long been deprecated.
Removed IMLFeature interface as it has long been deprecated."

I started replacing the uses by following instructions in the change logs, but I'm afraid I'm not particularly familiar with this codebase and I'm a little lost on how to fix marshalling so I can use the example code. 

![image](https://user-images.githubusercontent.com/41707698/159624918-da2d1d2e-f756-4051-8735-acb2cae52c8b.png)

**Comment by olokobayusuf** [comment]
We'll be publishing an update for the `@natsuite/hand-pose` predictor later today or tomorrow. Sorry about this!

**Comment by olokobayusuf** [comment]
[We've published the updated hand pose package on the Unity Asset Store](https://assetstore.unity.com/packages/tools/integration/hand-pose-realtime-hand-pose-recognition-215875).
