### ISSUE TITLE
Memory usage fills up with `@natsuite/robust-video-matting`

### ISSUE THREAD

**Issue by olokobayusuf** [natmlx/NatML#12]
Reported by [byfen on Unity Forums](https://forum.unity.com/threads/natml-machine-learning-runtime.1109339/#post-7967283).

**Comment by olokobayusuf** [comment]
Confirmed to be specific to Windows, not the RVM predictor.

**Comment by mchangxe** [comment]
just ran into this as well, can confirm on windows.

**Comment by olokobayusuf** [comment]
Fix confirmed in NatML 1.0.10 beta. Will close this issue once NatML 1.0.10 has been published.

**Comment by olokobayusuf** [comment]
NatML 1.0.10 has been released. Closing.
