### ISSUE TITLE
In natml1.0.10, Robust Video Matting error, cannot work.

### ISSUE THREAD

**Issue by isbyfen** [natmlx/NatML#13]
![1649906553(1)](https://user-images.githubusercontent.com/103488158/163307378-0bfa9421-5de0-4f47-a038-c8e2846f8b40.png)

**Comment by olokobayusuf** [comment]
@isbyfen I believe you mentioned that this was fixed by clearing your predictor cache? Please reopen this issue if it hasn't been fixed.
