### ISSUE TITLE
Is Pytorch really included?

### ISSUE THREAD

**Issue by RandGor** [natmlx/NatML#15]
Hello! I am looking for lib can run .pt on my NodeJS server. Found your project but I cannot see any info about .pt. 
Can you make it clear?

**Comment by olokobayusuf** [comment]
Hey there @RandGor , thanks for reaching out about this. We're actually moving serverless cloud ML inference into a separate product, Function. I'm curious to learn more about your use case, and make you a pilot. [Join the convo on Discord](https://discord.gg/gQ7kx9bp).
