### ISSUE TITLE
Android - every sample makes WebRequest error. "ai.natml.natml": "1.0.12",

### ISSUE THREAD

**Issue by TomaszWozniakMosina** [natmlx/NatML#19]
Hi,

Android - every sample (hands, segmentation, yolo) makes error as on attached picture.
Use "ai.natml.natml": "1.0.12", but checked also with 1.0.8, 1.0.9., 1.0.10, 1.0.11.

![image](https://user-images.githubusercontent.com/29869511/180138112-f3d81af0-82fa-471d-a5c7-d3375c6e0807.png)

**Comment by olokobayusuf** [comment]
Fix incoming in NatML 1.0.13, later today 😄

**Comment by acttoz** [comment]
same issue here

**Comment by olokobayusuf** [comment]
This has been fixed in [1.0.13](https://github.com/natmlx/NatML/releases/tag/1.0.13).
