### ISSUE TITLE
IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by november15** [natmlx/NatML#21]
Robust Video Matting - High Resolution Human Segmentation:
![image](https://user-images.githubusercontent.com/11310287/184273891-6153d5a7-2471-4fc5-b59b-f634ba95b991.png)
please help

**Comment by olokobayusuf** [comment]
Are you using a custom RVM model? Or are you fetching the model from NatML Hub? Can you share the exact example code that causes this error?

**Comment by november15** [comment]
> Are you using a custom RVM model? Or are you fetching the model from NatML Hub? Can you share the exact example code that causes this error?

yes,i use a unity package :Robust Video Matting - High Resolution Human Segmentation, then i find github :https://github.com/PeterL1n/RobustVideoMatting,and then from here download ONNX  RVM model, Dropping it into Unity.
after run, this bug appears。
![image](https://user-images.githubusercontent.com/11310287/185050931-55e589ab-c371-4fc2-96e3-df99f8e45d97.png)

**Comment by olokobayusuf** [comment]
The RVM model on NatML Hub has been modified to improve runtime performance. You must implement a predictor for the stock RVM model you downloaded.

**Comment by november15** [comment]
> The RVM model on NatML Hub has been modified to improve runtime performance. As such, you cannot use our implementation with the stock model. You must implement a predictor for the stock RVM model you downloaded.

i got it

**Comment by november15** [comment]
> > The RVM model on NatML Hub has been modified to improve runtime performance. As such, you cannot use our implementation with the stock model. You must implement a predictor for the stock RVM model you downloaded.
> 
> i got it

thank you
