### ISSUE TITLE
Hello. It works but show this message endless loop line.

### ISSUE THREAD

**Issue by acttoz** [natmlx/NatML#25]
What can I do to fix it?

Warn NdkImageReader Unable to acquire a lockedBuffer, very likely client tries to lock more than maxImages buffers
Warn NdkImageReader Unable to acquire a lockedBuffer, very likely client tries to lock more than maxImages buffers
Warn NdkImageReader Unable to acquire a lockedBuffer, very likely client tries to lock more than maxImages buffers
...

**Comment by olokobayusuf** [comment]
Duplicate of #22
