### ISSUE TITLE
Memory Leak on iOS 

### ISSUE THREAD

**Issue by jonmeggo** [natmlx/NatML#29]
We have come across a memory leak when using movenet and movenet-3D on iOS. For some reason, the model isn't being disposed of properly (even though we have the model?.Dispose() in the OnDisable method. To recreate - build the MoveNet-3D  sample project for iOS from here: https://github.com/natml-hub/MoveNet-3D. Then open the app and take note of the Documents and Data storage (Settings-> General->Storage->App Name. Then hard quit the app and reopen. You should see the Documents and Data storage jump up each time by 10-12mb. Have tried both embedded ML method and runtime. Happens with both.

**Comment by olokobayusuf** [comment]
Been able to reproduce it:
| Before 1st run | After 1st run | After 2nd run | After 3rd run |
|:--:|:--:|:--:|:--:|
| 
![IMG_7894](https://user-images.githubusercontent.com/17663473/193919331-44295548-7363-40c8-b344-edbe5b3a7e3d.PNG) | 
![IMG_7895](https://user-images.githubusercontent.com/17663473/193919366-ee2e72a4-1fa8-4384-b976-4c4fd8445bfb.PNG) | 
![IMG_7896](https://user-images.githubusercontent.com/17663473/193919386-b06df4ea-d2da-40db-8a9c-809bf72ffaf9.PNG) | 
![IMG_7897](https://user-images.githubusercontent.com/17663473/193919409-6395023c-1cb1-4cbb-b70b-994a02c4ba69.PNG) |

But interestingly, it's not a direct leak from NatML:
<img width="512" alt="Screen Shot 2022-10-04 at 4 25 36 PM" src="https://user-images.githubusercontent.com/17663473/193919515-7d8acca6-d405-416e-b7fe-321f3d51728b.png">

I believe it's caching from iOS that NatML doesn't explicitly delete. Will report back on a fix.

**Comment by olokobayusuf** [comment]
Fixed! Dropping in NatML 1.0.19 later today.

**Comment by olokobayusuf** [comment]
Fixed in NatML 1.0.19.
