### ISSUE TITLE
Running TinyYolov3 model crashes Unity

### ISSUE THREAD

**Issue by giga1992** [natmlx/NatML#3]
TinyYolov3 crashes Unity as soon as the scene starts. Looks like there's a problem with actually pulling the model from Hub.

**Comment by olokobayusuf** [comment]
This will be fixed in NatML 1.0.9.

**Comment by olokobayusuf** [comment]
We've archived `@natsuite/tiny-yolo-v3`.  Use [`@natsuite/yolox`](https://hub.natml.ai/@natsuite/yolox) instead.
