### ISSUE TITLE
Load model from local disk?

### ISSUE THREAD

**Issue by 1165048017** [natmlx/NatML#32]
I have tried load my model from unity asset in my local disk. 
The code like this :
```
using var model = modelData.Deserialize();
Debug.Log(model);
#var predictor = ?
```
the debug log give me that:
```
MLEdgeModel
Input: input.1: (1, 448, 448, 4) System.Byte
Input: input.4: (1, 448, 448, 4) System.Byte
Input: input.7: (1, 448, 448, 4) System.Byte
Output: 504: (1, 48, 28, 28) System.Single
Output: 499: (1, 24, 28, 28) System.Single
Output: 530: (1, 2016, 28, 28) System.Single
Output: 516: (1, 672, 28, 28) System.Single
UnityEngine.Debug:Log (object)
```
But how to write the predictor?  Look for some help~~~ thanks ^_^

**Comment by 1165048017** [comment]
I tried to write my predictor class accroding to [Hand-Pose](https://github.com/natml-hub/Hand-Pose/blob/22e085855b34f0b96406ac18abd10aeff1c3a335/Packages/ai.natml.vision.hand-pose/Runtime/HandPosePredictor.cs#L31) .
But the output features get total 0 values in the heat map.  so strange T_T

**Comment by 1165048017** [comment]
I tried to write my predictor class accroding to [Hand-Pose](https://github.com/natml-hub/Hand-Pose/blob/22e085855b34f0b96406ac18abd10aeff1c3a335/Packages/ai.natml.vision.hand-pose/Runtime/HandPosePredictor.cs#L31) .
But the output features get total 0 values in the heat map. so strange T_T

**Comment by olokobayusuf** [comment]
Hey @1165048017 , I'm closing this issue because it's technically not a NatML issue. Writing a predictor depends highly on what model you have and how it works, so it's almost impossible for someone who doesn't know much about your model to advise on how to write a predictor implementation.

**Comment by 1165048017** [comment]
> Hey @1165048017 , I'm closing this issue because it's technically not a NatML issue. Writing a predictor depends highly on what model you have and how it works, so it's almost impossible for someone who doesn't know much about your model to advise on how to write a predictor implementation.

The model performs correctly in python and barracuda~~ But NatML seems to much faster than barracuda, so that i want to try it!
Could I email you or your team for some help~~ 
After that, our team may consider the Enterprise Plan with NatML. This framework seems to be so flexible when developing on cross platform.
