### ISSUE TITLE
Add a RegionOfInterest method to MLImageFeature that takes an existing native array

### ISSUE THREAD

**Issue by joseph-o3h** [natmlx/NatML#35]
The RegionOfInterest method of MLImageFeature allocates a new array every time it is called, which increases GC pressure when called frequently. For better performance there should be a variant of this method that takes an existing array (`byte[]` and `NativeArray<byte>`) and fills it with the extracted image.

We have been able to do this in version 1.0.13 by creating a custom subclass of MLImageFeature, but that no longer works in the latest version (1.0.19).

**Comment by olokobayusuf** [comment]
Hey @joseph-o3h , I'll follow up on this issue with how we choose to implement this. It's a good feature request.

**Comment by olokobayusuf** [comment]
Hey @joseph-o3h we've added `MLImageFeature.CopyTo` which accepts a destination image feature. Docs incoming. [See the changelog](https://github.com/natmlx/NatML/releases/tag/1.1.0).
