### ISSUE TITLE
MLARImageFeature not available

### ISSUE THREAD

**Issue by VanIseghemThomas** [natmlx/NatML#38]
[The documentation](https://docs.natml.ai/natml/integrations/augmented-reality) states that MLARImageFeature can be used to easily convert an XRCpuImage to a image feature. But it seems this method is not yet available for use.

Is there any ETA for this?

I'm currently on 1.0.19

**Comment by olokobayusuf** [comment]
Hey @VanIseghemThomas that was a broken link. We refactored `MLARImageFeature` to [`MLXRCpuImageFeature`](https://docs.natml.ai/natml/api/mlfeature/mlxrcpuimagefeature) and moved it to the [ai.natml.natml.arfoundation](https://github.com/natmlx/NatML-ARFoundation) package.

**Comment by VanIseghemThomas** [comment]
Ok thanks for clearing that up!
