### ISSUE TITLE
MLXRCpuImageFeature causing memory leak on IOS

### ISSUE THREAD

**Issue by VanIseghemThomas** [natmlx/NatML#39]
Hi, it's me again!

I got everything working alongside AR-Foundation and I got to say I'm really impressed, by far the best NN solution for Unity! But I unfortunately I found a problem with the MLXRCpuImageFeature class. It causes a memory leak on IOS and I suspect it will on Android too. This causes the application to crash after a minute or so (depending on the available RAM). I checked all other things that could be the case for this memory leak but I can reliably narrow it down to creating a new MLXRCpuImageFeature.

<img width="656" alt="image" src="https://user-images.githubusercontent.com/55881698/208887071-e0a67572-225f-4e97-9c00-97e91bc043b8.png">

For context this is a simplified version of how I'm using it:

```cs
public ARCameraManager cameraManager;
private MLImageFeature currentFeature;

void Start(){
   cameraManager.frameReceived += FrameChanged;
}

void Update(){
    // Function that uses the current feature to do predictions
    // Does not cause the memory leak (verified)
    PredictAsync(currentFeature);
}

private void FrameChanged(ARCameraFrameEventArgs args){
    if (cameraManager.TryAcquireLatestCpuImage(out XRCpuImage image) && !Application.isEditor){
        // Commenting out this line get's rid of the memory leak
        currentFeature = new MLXRCpuImageFeature(image);
        image.Dispose();
    }    
}
```

In the meanwhile I'll figure out something to try and get rid of the memory leak but this is probably something that should be known about and fixed.

**Comment by olokobayusuf** [comment]
Fixed in [NatML-ARFoundation 1.0.1](https://github.com/natmlx/NatML-ARFoundation/releases/tag/1.0.1).
