### ISSUE TITLE
YOLOXPredictor memory leak when using async functions.

### ISSUE THREAD

**Issue by VanIseghemThomas** [natmlx/natml#41]
When creating an application I am able to use the `Predict` method without problems, this predicts like expected. But predicting, blocking the main thread of execution, isn't ideal. That's why I looked into "threading" it. Wrapping this `Predict` function in a Task, causes it to leak memory at a very fast rate. Remarkable this is only present on iOS (haven't tested Android) and not when used inside the simulated environment. Then it runs like it's supposed to.

![image](https://user-images.githubusercontent.com/55881698/218037915-a554fa14-f155-4b25-ae29-831ef1521751.png)

The following code shows my first way of doing things:

```csharp
// Causes memory leak
private async void PredictAsync(){
    await Task.Run(() => {
        Predict(currentFeature, (d) => {
            // Do something with the detections
            this.detections = d;
            isDetecting = false;
        });
    });
}

private void Predict(MLImageFeature feature, Action<(Rect rect, string label, float score)[]> callback){

    (Rect rect, string label, float score)[] detections = predictor.Predict(feature);

    if(callback != null)
        callback(detections);
}
```

Calling ```await PredictAsync()``` causes problems.
Then I got told there was a stock implementation for this, so I decided to give this a try.

```csharp
var predictor = new YOLOXPredictor(...).ToAsync();

...
...

// Triggered on event by XRCpuImageFetcher
private async void OnImageAvailable(XRCpuImage image){
    if(predictor.readyForPrediction && predictor != null){  
        // Might be moved to the image fetcher
        if(currentFeature == null){
            Debug.Log("Creating new feature");
            var conversionParams = new XRCpuImage.ConversionParams(image, TextureFormat.RGBA32, XRCpuImage.Transformation.None);
            currentFeature = new MLImageFeature(conversionParams.outputDimensions.x, conversionParams.outputDimensions.y);
            Debug.Log("Feature created");
        }

        if(cameraTexture == null){
            XRCpuImageToTexture(image);
            visualizer.image = cameraTexture;
        }

        Debug.Log("Copying image to feature");
        MLXRExtensions.CopyFrom(currentFeature, image);

        this.detections = await predictor.Predict(currentFeature);
    }
}
```

This results in the exact same behaviour.
I also verified it is probably not the XRCpuImage memory management since it works with the syncronous `Predict` method and it get's disposed by the event that provides it.

```csharp
using UnityEngine;
using UnityEngine.XR.ARFoundation;
using UnityEngine.XR.ARSubsystems;

public class XRCpuImageFetcher : MonoBehaviour
{
    public ARCameraManager cameraManager;

    void OnEnable()
    {
        cameraManager.frameReceived += FrameChanged;
    }

    void OnDisable()
    {
        cameraManager.frameReceived -= FrameChanged;
    }

    private void FrameChanged(ARCameraFrameEventArgs args){

        if (cameraManager.TryAcquireLatestCpuImage(out XRCpuImage image)){
            ImageAvailable?.Invoke(image);
            image.Dispose();
        }
    }

    public delegate void ImageAvailableDelegate(XRCpuImage image);
    public event ImageAvailableDelegate ImageAvailable;
}
```

If you need any more information, let me know and I'll look into it!

**Comment by olokobayusuf** [comment]
Fix dropping today:
<img width="1440" alt="Screenshot 2023-02-20 at 8 30 08 AM" src="https://user-images.githubusercontent.com/17663473/220122018-5f9b6661-516b-4115-94b0-4f79cc5104de.png">

**Comment by olokobayusuf** [comment]
[Fixed in NatML 1.1.2](https://github.com/natmlx/natml/releases/tag/1.1.2).

**Comment by VanIseghemThomas** [comment]
Awesome! Will verify asap. Thanks again!

**Comment by VanIseghemThomas** [comment]
Verified memory usage is stable now! Thanks @olokobayusuf.

**Comment by olokobayusuf** [comment]
Perfect!
