### ISSUE TITLE
NatDevice app token is invalid. Check your NatML access key and plan.

### ISSUE THREAD

**Issue by acttoz** [natmlx/natml#42]
Hello. I use "VideoKit Core" plan on 'natml.ai'.
I've been using it for the last 3 months with no issues, but a few days ago it started to happen.

**Comment by olokobayusuf** [comment]
Hey @acttoz what version of NatDevice are you using? Can you share your `manifest.json`?

**Comment by acttoz** [comment]
I use 1.2.5 version of NatDevice.

**Comment by olokobayusuf** [comment]
Can you upgrade to [NatDevice 1.3.2](https://github.com/natmlx/NatDevice#installing-natdevice)?

**Comment by acttoz** [comment]
I upgraded to NatDevice 1.3.2.
And I got message like this at all Natmlhub version 1.0.15 ~ 1.0.20

InvalidOperationException: NatMLHub native library is invalid.

**Comment by olokobayusuf** [comment]
Can you share the editor logs, and your `manifest.json`? Are you on macOS or Windows?

**Comment by acttoz** [comment]
Log
InvalidOperationException: NatMLHub native library is invalid.
NatML.Devices.Internal.NatDevice.CheckStatus (NatML.Devices.Internal.NatDevice+Status status) (at Library/PackageCache/ai.natml.natdevice@1.3.2/Runtime/Internal/NatDevice.cs:390)
NatML.Devices.MediaDeviceQuery+<DiscoverAudioDevices>d__20.MoveNext () (at Library/PackageCache/ai.natml.natdevice@1.3.2/Runtime/MediaDeviceQuery.cs:110)
System.Collections.Generic.List`1[T].AddEnumerable (System.Collections.Generic.IEnumerable`1[T] enumerable) (at <e40e5a8f982c4b618a930d29f9bd091c>:0)
System.Collections.Generic.List`1[T].InsertRange (System.Int32 index, System.Collections.Generic.IEnumerable`1[T] collection) (at <e40e5a8f982c4b618a930d29f9bd091c>:0)
System.Collections.Generic.List`1[T].AddRange (System.Collections.Generic.IEnumerable`1[T] collection) (at <e40e5a8f982c4b618a930d29f9bd091c>:0)
NatML.Devices.MediaDeviceQuery.DiscoverDevices (System.Predicate`1[T] filter, System.Int32 capacity) (at Library/PackageCache/ai.natml.natdevice@1.3.2/Runtime/MediaDeviceQuery.cs:101)
NatML.Devices.MediaDeviceQuery..ctor (System.Predicate`1[T] filter, System.Int32 capacity) (at Library/PackageCache/ai.natml.natdevice@1.3.2/Runtime/MediaDeviceQuery.cs:49)
NatML.MoveNet.Start () (at Assets/00script/Util/MoveNet.cs:53)


manifest
 "ai.natml.hub": "1.0.20",
    "ai.natml.natdevice": "1.3.2",
    "ai.natml.natml": "1.1.1",
    "ai.natml.vision.movenet": "1.0.4",


Windows ~

**Comment by acttoz** [comment]
It works now immediately.
But I don't know the reason.
Anyway, thank you!

**Comment by olokobayusuf** [comment]
Okay this sounds good. Feel free to reopen the issue if it pops up again.
