### ISSUE TITLE
AndroidRuntime 	at libNatML.NMLModelPredict(NMLModelPredict:296)

### ISSUE THREAD

**Issue by acttoz** [natmlx/natml#44]
I have upgraded Natml,Nathub and Natdevice as your advice.
I changed only the deprecated commands and didn't modify the rest, but what was working fine is now not working with an error.
It works on Windows, but on Android I get an error like below.

[logcat_android_error.txt](https://github.com/natmlx/natml/files/10776210/logcat_android_error.txt)

**Comment by acttoz** [comment]
I upgraded Natdevice, Nathub and Natml as your advice.
I only changed the deprecated instructions and didn't modify the rest, but what was working fine is now not working with an error.
It works on Windows and gives the error below on Android, I haven't checked IOS yet.


My code

`
void Start(){
            var query = new MediaDeviceQuery(MediaDeviceCriteria.FrontCamera);
            cameraDevice = query.current as CameraDevice
            cameraDevice.StartRunning(previewTextureOutput);
            model = await MLEdgeModel.Create("@natsuite/movenet");
            predictor = new MoveNetPredictor(model, smoothing);
}

private void Update(){
           var previewTexture = previewTextureOutput.texture;
            var inputFeature = new MLImageFeature(previewTexture.GetRawTextureData<byte>(), previewTexture.width, previewTexture.height);
            (inputFeature.mean, inputFeature.std) = model.normalization;
            // Detect
            var pose = predictor.Predict(inputFeature);
            // Visualize
            visualizer.Render(previewTexture, pose);
}
`

**Comment by acttoz** [comment]
I even verified that it works on IOS.
Error occurs on only android.

**Comment by olokobayusuf** [comment]
@acttoz can you share the full, unfiltered logs from app start to crash? Feel free to DM it to me on Discord if there is private info you would like to protect.

**Comment by olokobayusuf** [comment]
This should be fixed in [NatML 1.1.2](https://github.com/natmlx/natml/releases/tag/1.1.2).
