### ISSUE TITLE
Error AndroidRuntime 	at libNatML.NMLModelPredict(NMLModelPredict:296)

### ISSUE THREAD

**Issue by acttoz** [natmlx/natml#45]
I have upgraded to 1.1.2. But the error occur still.

[app.natsuite.posecam-logcat.txt](https://github.com/natmlx/natml/files/10792961/app.natsuite.posecam-logcat.txt)

**Comment by olokobayusuf** [comment]
Migrated to [natsuite/movenet](https://github.com/natml-hub/MoveNet).
