### ISSUE TITLE
I upgraded to 1.1.2, but the error is still not fixed.

### ISSUE THREAD

**Issue by acttoz** [natmlx/natml#46]
The error content is the same as below.

**Comment by acttoz** [comment]
There's no response, so I ask again.

**Comment by acttoz** [comment]
I'm running out of time on a project and this bug is holding me back.

**Comment by olokobayusuf** [comment]
@acttoz looking into it right now.

**Comment by olokobayusuf** [comment]
I'm closing this issue. Let's focus on the issue at [natml-hub/movenet](https://github.com/natml-hub/movenet/issues/7).
