### ISSUE TITLE
Edge Model Embedding Issue on iOS

### ISSUE THREAD

**Issue by Papasmun** [natmlx/natml#48]
Issue Outline: Unable to embed MLEdgeModel on iOS. According to to build logs, the model does get downloaded and embedded into the app binary. Seems that NatML isn't picking up the embedded model at runtime

Notes:
1) Works on Windows build, not on iOS
2) Using "@natsuite/movenet"
3) NatML version: 1.1.3
NatDevice version: 1.3.3
Hub version: 1.0.20

iOS log
[message.txt](https://github.com/natmlx/natml/files/10938327/message.txt)

Build log on Unity Editor
[Editor.log](https://github.com/natmlx/natml/files/10938326/Editor.log)

**Comment by olokobayusuf** [comment]
Hey @Papasmun I just noticed, it seems like your iOS device is not connected to the internet? Model embedding embeds the graph to reduce download times, but you still need an internet connection the very first time for NatML to fetch the session data needed to create the `MLEdgeModel`.

**Comment by olokobayusuf** [comment]
I'm closing this issue as we've made several improvements to model embedding in the [1.1.4 update](https://github.com/natmlx/natml/releases/tag/1.1.4).
